FROM ubuntu:jammy

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get -y --no-install-recommends install ca-certificates apt-transport-https
    
ENV PATH=/opt/intel/bin:$PATH
ENV LD_LIBRARY_PATH=/opt/intel/lib/intel64

RUN apt-get update && apt install curl libcap2-bin xz-utils -y

# Install dependencies
# Cmake version is recent enough on jammy (3.22 - apparently at least 3.17 was needed)
RUN apt-get update && apt-get install -y cmake \
                                         git \
                                         python3-pip  && \
    python3 -m pip install pytest deepdiff numpy
