FROM ubuntu:jammy

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get -y --no-install-recommends install ca-certificates apt-transport-https
    
ENV PATH=/opt/intel/bin:$PATH
ENV LD_LIBRARY_PATH=/opt/intel/lib/intel64

RUN apt-get update && apt install curl libcap2-bin xz-utils -y

# Install recent cmake (3.17)
# https://askubuntu.com/questions/355565/how-do-i-install-the-latest-version-of-cmake-from-the-command-line
# So need to install software-properties-common to add kitware repo https://askubuntu.com/questions/493460/how-to-install-add-apt-repository-using-the-terminal
# So need to install apt-transport-https https://unix.stackexchange.com/questions/263801/apt-get-fails-the-method-driver-usr-lib-apt-methods-https-could-not-be-found
RUN apt-get update && apt-get install -y wget build-essential libtool autoconf unzip \
                       software-properties-common \
                       apt-transport-https && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 605C66F00D6C9793 \
    0E98404D386FA1D9 648ACFD622F3D138 871920D1991BC93C && \ 
    wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - \
    | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null && \
    apt-add-repository 'deb https://apt.kitware.com/ubuntu/ jammy main' && \
    apt-get update && apt-get install -y cmake \
    	    	      	      	      	 git \
                                         python3-pip  && \
    python3 -m pip install pytest deepdiff numpy

