FROM ubuntu:focal

ENV PATH=/opt/intel/bin:$PATH
ENV LD_LIBRARY_PATH=/opt/intel/lib/intel64

# Install dependencies
# Cmake version is recent enough on jammy (3.22 - apparently at least 3.17 was needed)
RUN apt-get update && apt-get install -y cmake \
                                         git \
                                         python3-pip  && \
    python3 -m pip install pytest deepdiff numpy

