FROM ci_crysfml_focal_gfortran

SHELL ["/bin/bash", "-c"]

ARG CI_COMMIT_SHORT_SHA
ARG CI_COMMIT_REF_NAME

ENV CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA}
ENV CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME}

COPY ./ /app/
WORKDIR /app

ENV CRYSFML08=${WORKDIR}

CMD BuildServer/build_linux.sh gfortran && cp -a pycrysfml08_dist /artifacts/